// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.

package usecase

import (
	"context"
	appError "github.com/harryosmar/protobuf-go/error"
	pb "github.com/harryosmar/protobuf-go/gen/user"
	"github.com/harryosmar/protobuf-go/repository"
)

type UserServiceUsecase interface {
	CreateUser(context.Context, *pb.CreateUserRequest) (*pb.CreateUserResponse, error)
	GetUser(context.Context, *pb.GetUserRequest) (*pb.GetUserResponse, error)
}

type userServiceUsecase struct {
	repo repository.UserServiceRepository
}

func NewUserServiceUsecase(repo repository.UserServiceRepository) UserServiceUsecase {
	return &userServiceUsecase{repo: repo}
}

func (u *userServiceUsecase) CreateUser(ctx context.Context, req *pb.CreateUserRequest) (*pb.CreateUserResponse, error) {
	userEntity, err := u.repo.CreateUser(ctx, req)
	if err != nil {
		return nil, err
	}
	if userEntity == nil {
		return &pb.CreateUserResponse{}, nil
	}

	userPb, err := userEntity.ToPB(ctx)
	if err != nil {
		return nil, err
	}
	if userPb == nil {
		return &pb.CreateUserResponse{}, nil
	}

	return userPb, nil
}

func (u *userServiceUsecase) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.GetUserResponse, error) {
	userEntity, err := u.repo.GetUser(ctx, req)
	if err != nil {
		return nil, err
	}
	if userEntity == nil {
		return nil, appError.ErrNotFound
	}

	userPb, err := userEntity.ToPB(ctx)
	if err != nil {
		return nil, err
	}
	if userPb == nil {
		return &pb.CreateUserResponse{}, nil
	}

	return userPb, nil
}
