// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.

package usecase

import (
	"context"
	appError "github.com/harryosmar/protobuf-go/error"
	pb "github.com/harryosmar/protobuf-go/gen/user"
	"github.com/harryosmar/protobuf-go/repository"
)

// UserServiceUsecase defines the interface for user business logic
type UserServiceUsecase interface {
	// Methods matching the proto service definition
	CreateUser(context.Context, *pb.CreateUserRequestDTO) (*pb.CreateUserResponseDTO, error)
	GetUser(context.Context, *pb.GetUserRequestDTO) (*pb.GetUserResponse, error)
	UpdateUser(context.Context, *pb.UpdateUserRequestDTO) (*pb.UpdateUserResponseDTO, error)
	DeleteUser(context.Context, *pb.DeleteUserRequestDTO) (*pb.DeleteUserResponseDTO, error)
	ListUsers(context.Context, *pb.ListUsersRequestDTO) (*pb.ListUsersResponseDTO, error)
}

// userServiceUsecase implements UserServiceUsecase interface
type userServiceUsecase struct {
	userRepo repository.ServiceRepository[pb.UserEntityORM, uint32]
}

// NewUserServiceUsecase creates a new user usecase instance
func NewUserServiceUsecase(userRepo repository.ServiceRepository[pb.UserEntityORM, uint32]) UserServiceUsecase {
	return &userServiceUsecase{
		userRepo: userRepo,
	}
}

// Helper method to convert ORM to DTO
func (u *userServiceUsecase) ormToDTO(orm *pb.UserEntityORM) *pb.UserDTO {
	return &pb.UserDTO{
		Name:  orm.Name,
		Email: orm.Email,
		Id:    orm.Id,
	}
}

// Helper method to convert ORM list to DTO list
func (u *userServiceUsecase) ormToDTOList(ormRecords []pb.UserEntityORM) []*pb.UserDTO {
	var dtoRecords []*pb.UserDTO
	for _, record := range ormRecords {
		dtoRecords = append(dtoRecords, u.ormToDTO(&record))
	}
	return dtoRecords
}

// CreateUser implements the CreateUser RPC method from the proto service
func (u *userServiceUsecase) CreateUser(ctx context.Context, req *pb.CreateUserRequestDTO) (*pb.CreateUserResponseDTO, error) {
	// Create user entity from DTO
	userDTO := req.User
	userEntity := &pb.UserEntity{
		Id:        userDTO.Id,
		Name:      userDTO.Name,
		Email:     userDTO.Email,
		CreatedAt: userDTO.CreatedAt,
		UpdatedAt: userDTO.UpdatedAt,
	}

	// Convert to ORM model for database operations
	userORM, err := userEntity.ToORM(ctx)
	if err != nil {
		return nil, err
	}

	// Save to database using repository
	newUserORM, err := u.userRepo.Create(ctx, &userORM)
	if err != nil {
		return nil, err
	}

	return &pb.CreateUserResponseDTO{
		User: &pb.UserDTO{
			Name:  newUserORM.Name,
			Email: newUserORM.Email,
			Id:    newUserORM.Id,
		},
	}, nil
}

// GetUser implements the GetUser RPC method from the proto service
func (u *userServiceUsecase) GetUser(ctx context.Context, req *pb.GetUserRequestDTO) (*pb.GetUserResponse, error) {
	// Query database for user using repository
	userORM, err := u.userRepo.GetById(ctx, req.Id)
	if err != nil {
		return nil, err
	}
	if userORM == nil {
		return nil, appError.ErrUserNotFound
	}

	return &pb.GetUserResponse{
		User: u.ormToDTO(userORM),
	}, nil
}

// UpdateUser implements the UpdateUser RPC method from the proto service
func (u *userServiceUsecase) UpdateUser(ctx context.Context, req *pb.UpdateUserRequestDTO) (*pb.UpdateUserResponseDTO, error) {
	// Get existing user first
	userORM, err := u.userRepo.GetById(ctx, req.User.Id)
	if err != nil {
		return nil, err
	}
	if userORM == nil {
		return nil, appError.ErrUserNotFound
	}

	// Update fields
	userORM.Name = req.User.Name
	userORM.Email = req.User.Email

	// Update in database using repository
	if _, err := u.userRepo.Update(ctx, userORM); err != nil {
		return nil, err
	}

	return &pb.UpdateUserResponseDTO{
		User: req.User,
	}, nil
}

// DeleteUser implements the DeleteUser RPC method from the proto service
func (u *userServiceUsecase) DeleteUser(ctx context.Context, req *pb.DeleteUserRequestDTO) (*pb.DeleteUserResponseDTO, error) {
	// Delete from database using repository
	err := u.userRepo.Delete(ctx, req.Id)
	if err != nil {
		return nil, err
	}

	return &pb.DeleteUserResponseDTO{}, nil
}

// ListUsers implements the ListUsers RPC method from the proto service
func (u *userServiceUsecase) ListUsers(ctx context.Context, req *pb.ListUsersRequestDTO) (*pb.ListUsersResponseDTO, error) {
	ormRecords, paginator, err := u.userRepo.GetPerPage(
		ctx,
		req.Pagination.Page,
		req.Pagination.Limit,
		[]repository.OrderBy{},
		[]repository.Where{},
	)
	if err != nil {
		return nil, err
	}

	return &pb.ListUsersResponseDTO{
		Users: u.ormToDTOList(ormRecords),
		Pagination: &pb.PaginationResponse{
			Total: paginator.Total,
			Page:  paginator.Page,
			Limit: paginator.PerPage,
		},
	}, nil
}
