package generator

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateHandlers generates HTTP handler layer with DTOs
func GenerateHandlers(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_handler.scaffold.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"encoding/json"`)
	g.P(`	"net/http"`)
	g.P(`	"strconv"`)
	g.P(`	"github.com/gorilla/mux"`)
	g.P(")")
	g.P()

	for _, message := range file.Messages {
		if isEntity(message) {
			generateHandlerForEntity(g, message)
		}
	}
}

func generateHandlerForEntity(g *protogen.GeneratedFile, message *protogen.Message) {
	entityName := message.GoIdent.GoName
	handlerName := entityName + "Handler"

	g.P("// ", handlerName, " handles HTTP requests for ", entityName)
	g.P("type ", handlerName, " struct {")
	g.P("	service *", entityName, "Service")
	g.P("}")
	g.P()

	g.P("// New", handlerName, " creates a new ", handlerName)
	g.P("func New", handlerName, "(service *", entityName, "Service) *", handlerName, " {")
	g.P("	return &", handlerName, "{service: service}")
	g.P("}")
	g.P()

	// Generate CRUD handlers
	generateCreateHandler(g, entityName)
	generateGetHandler(g, entityName)
	generateUpdateHandler(g, entityName)
	generateDeleteHandler(g, entityName)
	generateListHandler(g, entityName)
}

func generateCreateHandler(g *protogen.GeneratedFile, entityName string) {
	g.P("// Create", entityName, " handles POST /", strings.ToLower(entityName), "s")
	g.P("func (h *", entityName, "Handler) Create", entityName, "(w http.ResponseWriter, r *http.Request) {")
	g.P("	var dto ", entityName, "DTO")
	g.P("	if err := json.NewDecoder(r.Body).Decode(&dto); err != nil {")
	g.P("		http.Error(w, err.Error(), http.StatusBadRequest)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	entity, err := h.service.Create(r.Context(), &dto)")
	g.P("	if err != nil {")
	g.P("		http.Error(w, err.Error(), http.StatusInternalServerError)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	w.Header().Set(\"Content-Type\", \"application/json\")")
	g.P("	w.WriteHeader(http.StatusCreated)")
	g.P("	json.NewEncoder(w).Encode(entity)")
	g.P("}")
	g.P()
}

func generateGetHandler(g *protogen.GeneratedFile, entityName string) {
	g.P("// Get", entityName, " handles GET /", strings.ToLower(entityName), "s/{id}")
	g.P("func (h *", entityName, "Handler) Get", entityName, "(w http.ResponseWriter, r *http.Request) {")
	g.P("	vars := mux.Vars(r)")
	g.P("	id, err := strconv.ParseInt(vars[\"id\"], 10, 64)")
	g.P("	if err != nil {")
	g.P("		http.Error(w, \"Invalid ID\", http.StatusBadRequest)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	entity, err := h.service.GetByID(r.Context(), id)")
	g.P("	if err != nil {")
	g.P("		http.Error(w, err.Error(), http.StatusNotFound)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	w.Header().Set(\"Content-Type\", \"application/json\")")
	g.P("	json.NewEncoder(w).Encode(entity)")
	g.P("}")
	g.P()
}

func generateUpdateHandler(g *protogen.GeneratedFile, entityName string) {
	g.P("// Update", entityName, " handles PUT /", strings.ToLower(entityName), "s/{id}")
	g.P("func (h *", entityName, "Handler) Update", entityName, "(w http.ResponseWriter, r *http.Request) {")
	g.P("	vars := mux.Vars(r)")
	g.P("	id, err := strconv.ParseInt(vars[\"id\"], 10, 64)")
	g.P("	if err != nil {")
	g.P("		http.Error(w, \"Invalid ID\", http.StatusBadRequest)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	var dto ", entityName, "DTO")
	g.P("	if err := json.NewDecoder(r.Body).Decode(&dto); err != nil {")
	g.P("		http.Error(w, err.Error(), http.StatusBadRequest)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	entity, err := h.service.Update(r.Context(), id, &dto)")
	g.P("	if err != nil {")
	g.P("		http.Error(w, err.Error(), http.StatusInternalServerError)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	w.Header().Set(\"Content-Type\", \"application/json\")")
	g.P("	json.NewEncoder(w).Encode(entity)")
	g.P("}")
	g.P()
}

func generateDeleteHandler(g *protogen.GeneratedFile, entityName string) {
	g.P("// Delete", entityName, " handles DELETE /", strings.ToLower(entityName), "s/{id}")
	g.P("func (h *", entityName, "Handler) Delete", entityName, "(w http.ResponseWriter, r *http.Request) {")
	g.P("	vars := mux.Vars(r)")
	g.P("	id, err := strconv.ParseInt(vars[\"id\"], 10, 64)")
	g.P("	if err != nil {")
	g.P("		http.Error(w, \"Invalid ID\", http.StatusBadRequest)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	if err := h.service.Delete(r.Context(), id); err != nil {")
	g.P("		http.Error(w, err.Error(), http.StatusInternalServerError)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	w.WriteHeader(http.StatusNoContent)")
	g.P("}")
	g.P()
}

func generateListHandler(g *protogen.GeneratedFile, entityName string) {
	g.P("// List", entityName, "s handles GET /", strings.ToLower(entityName), "s")
	g.P("func (h *", entityName, "Handler) List", entityName, "s(w http.ResponseWriter, r *http.Request) {")
	g.P("	page, _ := strconv.Atoi(r.URL.Query().Get(\"page\"))")
	g.P("	pageSize, _ := strconv.Atoi(r.URL.Query().Get(\"page_size\"))")
	g.P("	if page < 1 {")
	g.P("		page = 1")
	g.P("	}")
	g.P("	if pageSize < 1 || pageSize > 100 {")
	g.P("		pageSize = 10")
	g.P("	}")
	g.P()
	g.P("	entities, total, err := h.service.List(r.Context(), page, pageSize)")
	g.P("	if err != nil {")
	g.P("		http.Error(w, err.Error(), http.StatusInternalServerError)")
	g.P("		return")
	g.P("	}")
	g.P()
	g.P("	response := map[string]interface{}{")
	g.P("		\"data\":       entities,")
	g.P("		\"page\":       page,")
	g.P("		\"page_size\":  pageSize,")
	g.P("		\"total\":      total,")
	g.P("	}")
	g.P()
	g.P("	w.Header().Set(\"Content-Type\", \"application/json\")")
	g.P("	json.NewEncoder(w).Encode(response)")
	g.P("}")
	g.P()
}

func isEntity(message *protogen.Message) bool {
	// Check if message has entity annotation
	// For now, we'll consider messages with "Entity" suffix as entities
	return strings.HasSuffix(message.GoIdent.GoName, "Entity") || 
		   hasEntityOption(message)
}

func hasEntityOption(message *protogen.Message) bool {
	// TODO: Check for custom proto options like (scaffold.entity) = true
	// This requires defining custom proto options
	return false
}
