package generator

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateRepositories generates repository layer with database operations
func GenerateRepositories(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_repository.scaffold.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"database/sql"`)
	g.P(")")
	g.P()

	for _, message := range file.Messages {
		if isEntity(message) {
			generateRepositoryForEntity(g, message)
		}
	}
}

func generateRepositoryForEntity(g *protogen.GeneratedFile, message *protogen.Message) {
	entityName := message.GoIdent.GoName
	repoName := entityName + "Repository"
	tableName := toSnakeCase(entityName)

	g.P("// ", repoName, " handles database operations for ", entityName)
	g.P("type ", repoName, " struct {")
	g.P("	db *sql.DB")
	g.P("}")
	g.P()

	g.P("// New", repoName, " creates a new ", repoName)
	g.P("func New", repoName, "(db *sql.DB) *", repoName, " {")
	g.P("	return &", repoName, "{db: db}")
	g.P("}")
	g.P()

	// Generate CRUD methods
	generateRepoCreate(g, entityName, tableName)
	generateRepoFindByID(g, entityName, tableName)
	generateRepoUpdate(g, entityName, tableName)
	generateRepoDelete(g, entityName, tableName)
	generateRepoFindAll(g, entityName, tableName)
	generateRepoCount(g, entityName, tableName)
}

func generateRepoCreate(g *protogen.GeneratedFile, entityName, tableName string) {
	g.P("// Create inserts a new ", entityName, " into the database")
	g.P("func (r *", entityName, "Repository) Create(ctx context.Context, entity *", entityName, ") error {")
	g.P("	query := `INSERT INTO ", tableName, "s (/* columns */) VALUES (/* values */)`")
	g.P("	result, err := r.db.ExecContext(ctx, query /* , entity fields */)")
	g.P("	if err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P()
	g.P("	id, err := result.LastInsertId()")
	g.P("	if err != nil {")
	g.P("		return err")
	g.P("	}")
	g.P()
	g.P("	// Set entity ID")
	g.P("	_ = id // TODO: Set entity.ID = id")
	g.P("	return nil")
	g.P("}")
	g.P()
}

func generateRepoFindByID(g *protogen.GeneratedFile, entityName, tableName string) {
	g.P("// FindByID retrieves a ", entityName, " by ID")
	g.P("func (r *", entityName, "Repository) FindByID(ctx context.Context, id int64) (*", entityName, ", error) {")
	g.P("	query := `SELECT /* columns */ FROM ", tableName, "s WHERE id = $1`")
	g.P("	entity := &", entityName, "{}")
	g.P()
	g.P("	err := r.db.QueryRowContext(ctx, query, id).Scan(/* &entity fields */)")
	g.P("	if err == sql.ErrNoRows {")
	g.P("		return nil, nil")
	g.P("	}")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	return entity, nil")
	g.P("}")
	g.P()
}

func generateRepoUpdate(g *protogen.GeneratedFile, entityName, tableName string) {
	g.P("// Update updates an existing ", entityName)
	g.P("func (r *", entityName, "Repository) Update(ctx context.Context, entity *", entityName, ") error {")
	g.P("	query := `UPDATE ", tableName, "s SET /* columns = values */ WHERE id = $1`")
	g.P("	_, err := r.db.ExecContext(ctx, query /* , entity fields, entity.ID */)")
	g.P("	return err")
	g.P("}")
	g.P()
}

func generateRepoDelete(g *protogen.GeneratedFile, entityName, tableName string) {
	g.P("// Delete removes a ", entityName, " by ID")
	g.P("func (r *", entityName, "Repository) Delete(ctx context.Context, id int64) error {")
	g.P("	query := `DELETE FROM ", tableName, "s WHERE id = $1`")
	g.P("	_, err := r.db.ExecContext(ctx, query, id)")
	g.P("	return err")
	g.P("}")
	g.P()
}

func generateRepoFindAll(g *protogen.GeneratedFile, entityName, tableName string) {
	g.P("// FindAll retrieves all ", entityName, "s with pagination")
	g.P("func (r *", entityName, "Repository) FindAll(ctx context.Context, offset, limit int) ([]*", entityName, ", error) {")
	g.P("	query := `SELECT /* columns */ FROM ", tableName, "s ORDER BY id LIMIT $1 OFFSET $2`")
	g.P("	rows, err := r.db.QueryContext(ctx, query, limit, offset)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	defer rows.Close()")
	g.P()
	g.P("	var entities []*", entityName)
	g.P("	for rows.Next() {")
	g.P("		entity := &", entityName, "{}")
	g.P("		if err := rows.Scan(/* &entity fields */); err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P("		entities = append(entities, entity)")
	g.P("	}")
	g.P()
	g.P("	return entities, rows.Err()")
	g.P("}")
	g.P()
}

func generateRepoCount(g *protogen.GeneratedFile, entityName, tableName string) {
	g.P("// Count returns the total number of ", entityName, "s")
	g.P("func (r *", entityName, "Repository) Count(ctx context.Context) (int64, error) {")
	g.P("	query := `SELECT COUNT(*) FROM ", tableName, "s`")
	g.P("	var count int64")
	g.P("	err := r.db.QueryRowContext(ctx, query).Scan(&count)")
	g.P("	return count, err")
	g.P("}")
	g.P()
}

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteRune('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}
