package generator

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateServices generates service layer with business logic
func GenerateServices(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_service.scaffold.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"errors"`)
	g.P(")")
	g.P()

	for _, message := range file.Messages {
		if isEntity(message) {
			generateServiceForEntity(g, message)
		}
	}
}

func generateServiceForEntity(g *protogen.GeneratedFile, message *protogen.Message) {
	entityName := message.GoIdent.GoName
	serviceName := entityName + "Service"

	g.P("// ", serviceName, " provides business logic for ", entityName)
	g.P("type ", serviceName, " struct {")
	g.P("	repo *", entityName, "Repository")
	g.P("}")
	g.P()

	g.P("// New", serviceName, " creates a new ", serviceName)
	g.P("func New", serviceName, "(repo *", entityName, "Repository) *", serviceName, " {")
	g.P("	return &", serviceName, "{repo: repo}")
	g.P("}")
	g.P()

	// Generate CRUD methods
	generateServiceCreate(g, entityName)
	generateServiceGetByID(g, entityName)
	generateServiceUpdate(g, entityName)
	generateServiceDelete(g, entityName)
	generateServiceList(g, entityName)
}

func generateServiceCreate(g *protogen.GeneratedFile, entityName string) {
	g.P("// Create creates a new ", entityName)
	g.P("func (s *", entityName, "Service) Create(ctx context.Context, dto *", entityName, "DTO) (*", entityName, ", error) {")
	g.P("	// TODO: Add validation logic")
	g.P("	entity := &", entityName, "{")
	g.P("		// Map DTO fields to entity")
	g.P("	}")
	g.P()
	g.P("	if err := s.repo.Create(ctx, entity); err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	return entity, nil")
	g.P("}")
	g.P()
}

func generateServiceGetByID(g *protogen.GeneratedFile, entityName string) {
	g.P("// GetByID retrieves a ", entityName, " by ID")
	g.P("func (s *", entityName, "Service) GetByID(ctx context.Context, id int64) (*", entityName, ", error) {")
	g.P("	entity, err := s.repo.FindByID(ctx, id)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	if entity == nil {")
	g.P("		return nil, errors.New(\"", strings.ToLower(entityName), " not found\")")
	g.P("	}")
	g.P("	return entity, nil")
	g.P("}")
	g.P()
}

func generateServiceUpdate(g *protogen.GeneratedFile, entityName string) {
	g.P("// Update updates an existing ", entityName)
	g.P("func (s *", entityName, "Service) Update(ctx context.Context, id int64, dto *", entityName, "DTO) (*", entityName, ", error) {")
	g.P("	entity, err := s.repo.FindByID(ctx, id)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	if entity == nil {")
	g.P("		return nil, errors.New(\"", strings.ToLower(entityName), " not found\")")
	g.P("	}")
	g.P()
	g.P("	// TODO: Update entity fields from DTO")
	g.P()
	g.P("	if err := s.repo.Update(ctx, entity); err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P()
	g.P("	return entity, nil")
	g.P("}")
	g.P()
}

func generateServiceDelete(g *protogen.GeneratedFile, entityName string) {
	g.P("// Delete deletes a ", entityName, " by ID")
	g.P("func (s *", entityName, "Service) Delete(ctx context.Context, id int64) error {")
	g.P("	return s.repo.Delete(ctx, id)")
	g.P("}")
	g.P()
}

func generateServiceList(g *protogen.GeneratedFile, entityName string) {
	g.P("// List retrieves a paginated list of ", entityName, "s")
	g.P("func (s *", entityName, "Service) List(ctx context.Context, page, pageSize int) ([]*", entityName, ", int64, error) {")
	g.P("	offset := (page - 1) * pageSize")
	g.P("	entities, err := s.repo.FindAll(ctx, offset, pageSize)")
	g.P("	if err != nil {")
	g.P("		return nil, 0, err")
	g.P("	}")
	g.P()
	g.P("	total, err := s.repo.Count(ctx)")
	g.P("	if err != nil {")
	g.P("		return nil, 0, err")
	g.P("	}")
	g.P()
	g.P("	return entities, total, nil")
	g.P("}")
	g.P()
}
