// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.

package server

import (
	"context"
	appError "github.com/harryosmar/protobuf-go/error"
	pb "github.com/harryosmar/protobuf-go/gen/user"
	"github.com/harryosmar/protobuf-go/logger"
	"github.com/harryosmar/protobuf-go/usecase"
)

type UserServiceServer interface {
	CreateUser(context.Context, *pb.CreateUserRequest) (*pb.CreateUserResponse, error)
	GetUser(context.Context, *pb.GetUserRequest) (*pb.GetUserResponse, error)
}

type userServiceServer struct {
	pb.UnimplementedUserServiceServer
	usecase usecase.UserServiceUsecase
}

func NewUserServiceServer(usecase usecase.UserServiceUsecase) UserServiceServer {
	return &userServiceServer{usecase: usecase}
}

func (u *userServiceServer) CreateUser(ctx context.Context, req *pb.CreateUserRequest) (*pb.CreateUserResponse, error) {
	var (
		err error
		log = logger.FromContext(ctx)
	)
	log.Info("userServiceServer.CreateUser called")

	defer func() {
		if err != nil {
			log.Error(err.Error())
		}
	}()

	if err = req.Validate(); err != nil {
		return nil, appError.ErrInvalidArgument.WithMessage("validation failed: %v", err)
	}

	return u.usecase.CreateUser(ctx, req)
}

func (u *userServiceServer) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.GetUserResponse, error) {
	var (
		err error
		log = logger.FromContext(ctx)
	)
	log.Info("userServiceServer.GetUser called")

	defer func() {
		if err != nil {
			log.Error(err.Error())
		}
	}()

	if err = req.Validate(); err != nil {
		return nil, appError.ErrInvalidArgument.WithMessage("validation failed: %v", err)
	}

	return u.usecase.GetUser(ctx, req)
}
