// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.

package repository

import (
	userpb "github.com/harryosmar/protobuf-go/gen/user"
	"gorm.io/gorm"
)

// userServiceRepositoryMySQL implements UserServiceRepository interface
type userServiceRepositoryMySQL struct {
	*BaseGorm[userpb.UserEntityORM, uint32]
}

// NewUserServiceRepositoryMySQL creates a new user repository instance
func NewUserServiceRepositoryMySQL(db *gorm.DB) ServiceRepository[userpb.UserEntityORM, uint32] {
	return &userServiceRepositoryMySQL{
		NewBaseGorm[userpb.UserEntityORM, uint32](db),
	}
}
