// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.

package usecase

import (
	"context"
	"errors"
	pb "github.com/harryosmar/protobuf-go/gen/user"
	"gorm.io/gorm"
)

type UserServiceRepository interface {
	Create(context.Context, *pb.UserEntityORM) (*pb.UserEntityORM, int64, error)
	Update(context.Context, *pb.UserEntityORM) (*pb.UserEntityORM, int64, error)
	Get(ctx context.Context, id string) (*pb.UserEntityORM, error)
	Delete(ctx context.Context, id int64) (int64, error)
}

type userServiceRepository struct {
	db *gorm.DB
}

func NewUserServiceRepository(db *gorm.DB) UserServiceRepository {
	return &userServiceRepository{db: db}
}

func (u *userServiceRepository) Create(ctx context.Context, user *pb.UserEntityORM) (*pb.UserEntityORM, int64, error) {
	var (
		db = u.db.WithContext(ctx)
	)

	result := db.Create(user)
	if result.Error != nil {
		return nil, 0, err
	}
	return user, result.RowsAffected, nil
}

func (u *userServiceRepository) Update(ctx context.Context, user *pb.UserEntityORM) (*pb.UserEntityORM, int64, error) {
	var (
		db = u.db.WithContext(ctx)
	)

	result := db.Save(user)
	if result.Error != nil {
		return nil, 0, err
	}
	return user, result.RowsAffected, nil
}

func (u *userServiceRepository) Get(ctx context.Context, id string) (*pb.UserEntityORM, error) {
	var (
		db = u.db.WithContext(ctx)
	)

	var user userpb.UserEntityORM
	if err := db.First(&user, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return &user, nil
}

func (u *userServiceRepository) Delete(ctx context.Context, id int64) (int64, error) {
	var (
		db = u.db.WithContext(ctx)
	)

	result := db.Delete(&userpb.UserEntityORM{}, id)
	if result.Error != nil {
		return 0, result.Error
	}

	return result.RowsAffected, nil
}
