// Code generated by protoc-gen-go-scaffold. DO NOT EDIT.

package main

import (
	appError "github.com/harryosmar/protobuf-go/error"
)

// init function registers all service-specific error codes
func init() {
	// Register UserService error codes
	appError.InitUserServiceCode()
}
